name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:  
      - name: Deploy to staging
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker version
